### ISSUE TITLE
Throwing a Meteor.Error inside meteor meteor method cause UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by jaybeemind** [Meteor-Community-Packages/meteor-method-hooks#8]
Hi, I'm using `beforeAllMethods` to dynamically check a user's access rights.
Putting `throw new Meteor.Error()` inside the callback of a `Meteor.call` causes this:

`
(node:22100) UnhandledPromiseRejectionWarning: Error: You are not authorized to do that. [403]
W20210429-12:02:28.013(8)? (STDERR)     at imports/startup/server/register-api.js:38:28
W20210429-12:02:28.013(8)? (STDERR)     at packages/ddp-server/livedata_server.js:1634:19
W20210429-12:02:28.013(8)? (STDERR)     at C:\Users\Administrator\AppData\Local\.meteor\packages\promise\0.11.2\npm\node_modules\meteor-promise\fiber_pool.js:43:40
W20210429-12:02:28.014(8)? (STDERR) (node:22100) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
W20210429-12:02:28.015(8)? (STDERR) (node:22100) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
`

Pseudo code:

```
Meteor.beforeAllMethods(function () {
  const action = this._methodName

  // exclude these methods
  if (excludeMethods.includes(action)) return

  Meteor.call('checkUserRole', [action], (error, result) => {
      console.log('running roles check')
      if (error) throw new Meteor.Error(501, 'Something went wrong while processing your request.')

      // throw meteor error if user has no access to this action
      if (!result) throw new Meteor.Error(403, 'You are not authorized to do that.') // this causes UnhandledPromiseRejectionWarning

      return
    })
}) // /Meteor.beforeAllMethods(function () {
```

I'm using Meteor 2.2.

I can't remember if this wasn't an issue before though, since I've used this package in Meteor 1.8.
Thanks!

**Comment by jaybeemind** [comment]
Closing this, I resolved my problem using fibers.
Cheers!
